---
- name: Prepare script for updating local mirrors list
  template:
    src: "{{ mirrors_timer_name }}_script.j2"
    dest: "{{ update_mirrors_list_script_path }}"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: 0740
    force: 'yes'

- name: Prepare systemd units
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dst }}"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: 0640
    force: 'yes'
  vars:
    description: Update a local mirrors list
  with_items:
    - dst: "{{ mirrors_timer_name }}.service"
      src: "{{ mirrors_timer_name }}_service.j2"
    - dst: "{{ mirrors_timer_name }}.timer"
      src: "{{ mirrors_timer_name }}_timer.j2"

- name: Enable systemd timer
  systemd:
    name: "{{ mirrors_timer_name }}.timer"
    state: started
    enabled: true
    masked: false
    daemon_reload: true
