---
- name: Prepare script for updating local mirrors list
  template:
    src: "{{ mirror_list_update }}.sh.j2"
    dest: "{{ scripts_path }}/{{ mirror_list_update }}.sh"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    setype: bin_t
    seuser: system_u
    mode: 0740

- name: Prepare systemd units
  template:
    src: "{{ item.src }}"
    dest: "{{ systemd_services_path }}/{{ item.dst }}"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: 0640
    setype: "{{ item.setype }}"
    seuser: "{{ item.seuser }}"
  vars:
    description: Update a local mirrors list
  with_items:
    - dst: "{{ mirror_list_update }}.service"
      src: "{{ mirror_list_update }}.service.j2"
      setype: systemd_unit_file_t
      seuser: system_u
    - dst: "{{ mirror_list_update }}.timer"
      src: "{{ mirror_list_update }}.timer.j2"
      setype: systemd_unit_file_t
      seuser: system_u
    - dst: "{{ mirror_service_git_updater }}.service"
      src: "{{ mirror_service_git_updater }}.service.j2"
      setype: systemd_unit_file_t
      seuser: system_u
    - dst: "{{ mirror_service_git_updater }}.timer"
      src: "{{ mirror_service_git_updater }}.timer.j2"
      setype: systemd_unit_file_t
      seuser: system_u

- name: Enable git updater systemd timer
  systemd:
    name: "{{ mirror_service_git_updater }}.timer"
    state: started
    enabled: true
    masked: false
    daemon_reload: true
