---
- name: Prepare script for updating MaxMind DBs
  template:
    src: "{{ dbs_update }}.sh.j2"
    dest: "{{ scripts_path }}/{{ dbs_update }}.sh"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    setype: bin_t
    seuser: system_u
    mode: 0740

- name: Prepare systemd units
  template:
    src: "{{ item.src }}"
    dest: "{{ systemd_services_path }}/{{ item.dst }}"
    group: "{{ service_user }}"
    owner: "{{ service_user }}"
    mode: 0640
    setype: "{{ item.setype }}"
    seuser: "{{ item.seuser }}"
  vars:
    description: Update the MaxMind DBs
  with_items:
    - dst: "{{ dbs_update }}.service"
      src: "{{ dbs_update }}.service.j2"
      setype: systemd_unit_file_t
      seuser: system_u
    - dst: "{{ dbs_update }}.timer"
      src: "{{ dbs_update }}.timer.j2"
      setype: systemd_unit_file_t
      seuser: system_u

- name: Enable systemd timer
  systemd:
    name: "{{ dbs_update }}.timer"
    state: started
    enabled: true
    masked: false
    daemon_reload: true

- name: Run update MaxMind DBs
  systemd:
    name: "{{ dbs_update }}.service"
    state: restarted
