---
- name: Check some mirrors in a request (MirrorList)
  uri:
    url: "http://localhost/mirrorlist/8/baseos"
    headers:
      X-Forwarded-For: "{{ item.value }}"
    method: GET
    return_content: yes
  register: result
  failed_when: "item.key not in result.content"
  loop: "{{ mirrors | dict2items }}"
  vars:
    mirrors:
      # some public mirror
      atl.mirrors.knownhost.com: "67.222.0.49"
      mirror.fcix.net: "23.152.160.16"

- name: Check vault versions
  uri:
    url: "http://localhost/mirrorlist/{{ item }}/baseos"
    method: GET
    return_content: yes
  register: result
  failed_when: "'http://vault.almalinux.org/' ~ item ~ '/BaseOS/$basearch/os/' not in (result.content | trim)"
  with_items:
    - "8.3"
    - "8.4"
    - "9.5"
    - "10.0"

- name: Check ISOs page
  uri:
    url: "http://localhost/isos.html"
    method: GET
    return_content: yes
  register: result
  failed_when: "'AlmaLinux ISO links' not in result.content"

- name: Check arch/version ISOs page
  uri:
    url: "http://localhost/isos/x86_64/9.html"
    method: GET
    return_content: yes
  register: result
  failed_when: "'AlmaLinux ISO links' not in result.content"

- name: Check some mirrors in a request (ISOList)
  uri:
    url: "http://localhost/isos/x86_64/8"
    headers:
      X-Forwarded-For: "{{ item.value }}"
    method: GET
    return_content: yes
  register: result
  failed_when: "item.key not in result.content"
  loop: "{{ mirrors | dict2items }}"
  vars:
    mirrors:
      # some public mirror
      mirrors.storpool.com: "185.117.80.53"
