"""Private mirrors

Revision ID: 819b9d9d7121
Revises:
Create Date: 2021-07-13 14:58:10.902027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519b9d9d7123'
down_revision = '519b9d9d7122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mirrors', sa.Column('private', sa.Boolean(),
                                       nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mirrors', 'private')
    # ### end Alembic commands ###

