"""asn_subnets

Revision ID: 819b9d9d7121
Revises:
Create Date: 2021-07-13 14:58:10.902027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819b9d9d7121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mirrors', sa.Column(
        'asn',
        sa.String(),
        nullable=True,
    ))
    op.create_table('subnets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subnet', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mirrors_subnets',
                    sa.Column('mirror_id', sa.Integer(), nullable=True),
                    sa.Column('subnet_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(('mirror_id',), ['mirrors.id'],
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(('subnet_id',), ['subnets.id'],
                                            ondelete='CASCADE')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mirrors_subnets')
    op.drop_table('subnets')
    op.drop_column('mirrors', 'asn')
    # ### end Alembic commands ###
